### PR TITLE
Background Animations

### PR DESCRIPTION
**Pull request by Tanya347**
Hi, this site was quite literally perfect, I've just added a background animation to make it more interesting and attractive.

The box transition goes from top to bottom:
image

And animations on hover:
image

Hope you like it, if so please merge my code. Thanks :)

### CODE REVIEW

**Comment by VivekChatterjee** [comment]
Awesome work @Tanya347 , it looks great to have this animation.
Just one thing on hover the color that shows up is too bright, if we could make it a few shades darker so that it blends perfectly with the background animation, I think it would be great then.

**Comment by Tanya347** [comment]
Hey @VivekChatterjee , I have made the hover color same as the background animation so that they can blend well and it's not too bright:

image

**Comment by Tanya347** [comment]
Also I don't know how the conflicts occurred but please accept the incoming changes, as I have removed a few parts from the original code.

**Comment by VivekChatterjee** [comment]
Perfect.

**Pull request merged**
