### PR TITLE
Fix: Movie display UI

### PR DESCRIPTION
**Pull request by this-ezzy**
## The display of the movie upon successful request needed some fix.

- I increased the width of the movie image to span 100%
- I arranged the rating, year published, duration and rated properly
- I added an overflow property for better scrolling
- I added a no-repeat for the body background.

**this is the current state of the UI**

Screenshot 2023-10-16 080857

Screenshot 2023-10-16 141706

**this is the implemented changes**

Screenshot 2023-10-16 141606

Screenshot 2023-10-16 141650

### CODE REVIEW

**Comment by Ezzywealth** [comment]
@VivekChatterjee can you please give me some hint why the deployment is failing?
I think it is related to the node version but i am not so sure

**Comment by VivekChatterjee** [comment]
@Ezzywealth I checked the site after your changes for the bug you pointed but the previous styling seemed consistent and nicer although the text was being distorted but now the image is being cropped abruptly, leaving out the vital parts.
So, I want to suggest a thing: can the card width be made variable so as to keep the image as it is (on the left) and card width can change to keep the text (on the right) in a proper format.

**Comment by Ezzywealth** [comment]
@VivekChatterjee , this is the current state of the layout, what do you think

Screenshot 2023-10-17 095445

**Comment by VivekChatterjee** [comment]
Great @Ezzywealth

**Pull request merged**
